### PR TITLE
Removed duplicated items from alien containment list

### LINKED ISSUE #1302: Alien Containment accounting: 2x each item and Brainsucker Pod = 80%
- OS: Windows 10 x64 2020H2
 - OpenApoc Version 20231225-3
 - No mods

**Describe the bug**
Alien containment sometimes counts items in 2 categories that each take their own separate % of space. Also, Brainsucker Pods currently count as 80% of containment space _each_.

screenshot002

### PR DESCRIPTION
**Pull request by ayrtondenner**
Fixes #1302 and #608

Aliens in containment list were appearing duplicated whenever an alien type exists in more than one base.

Before:
image

After:
image

### CODE REVIEW

**Comment by FilmBoy84** [comment]
I have tested this today
Appears to work
Though i am having trouble finding where brainsucker pods now are (since removed from alien containment list)
They no longer appear to be in Agent Equipment list either (either on agent equip or agent equipment market screens); despite two launchers being recovered (which do appear)

Going to do further testing before i merge as im not sure if pods now disappear into the void

**Comment by FilmBoy84** [comment]
Okay, a little delay in getting saves to you, but here is what I have discovered

There is an agent in this mission of the ORIGINAL GAME holding a brainsucker pod, keep him alive and finish the mission... On returning to base, the brainsucker pod is placed in ALIEN CONTAINMENT and is available for research

[SAVEGAME 1.zip](https://github.com/OpenApoc/OpenApoc/files/14711133/SAVEGAME.1.zip)
image

In OpenApoc, under the build for PR, again, please find attached a savegame with an agent that has a brainsucker pod in their inventory, please finish the mission and you will see on return from that mission the pod neither appears in Alien Containment OR Agent inventory - IT SHOULD DO but this PR sadly makes it disappear completely
[Test.zip](https://github.com/OpenApoc/OpenApoc/files/14711377/Test.zip)
Win64 build: https://ci.appveyor.com/project/OpenApoc/openapoc/builds/49418718/artifacts

**Comment by ayrtondenner** [comment]
Wait, so when a brainsucker pod should appear in the Alien Containment list? Only when it's alive?

**Comment by FilmBoy84** [comment]
There is no pod autopsy, so yes, pods appear in the Alien Containment as they can only be "alive".

The problem referred to in #1302 and several linked issues is that for some reason Brainsucker Pod (Alive) was taking up too much space in Alien Containment rather than it should not be there

I need to check what happens when the pod is researched though - I have a nagging feeling research then adds a "Brainsucker (Alive)" to the Alien Containment on completion research of which should then return a "Brainsucker (Dead)" to the Alien Containment

But that sounds too easy for getting live brainsuckers, so i really need to investigate it as it may be the case that researching the live pod just results in it's destruction (unless you want to test with the Original Game save i provided above first?)

**Comment by ayrtondenner** [comment]
Ok, so should I reverse changes made in https://github.com/OpenApoc/OpenApoc/pull/1372?
Because then Brainsucker Pods will re-appear.

And then I will have to check the values being used for Brainsucker Pods when calculating storage usage for Alien Containment.

**Comment by FilmBoy84** [comment]
Agreed, I'm starting to think we may have to revert #1372 too

Although before anything we need to check the OG logic to save further increasing the workload with anything else missed regarding pods (they are fairly unique in being ammo, equipment and a live alien)

Apologies again, it was my bad in testing #1372 - I assumed removing them from Alien Containment was needed, tested that it removed them, and failed to realise that they are mean to be in there just not consume all the capacity they do 😓

**Comment by ayrtondenner** [comment]
image
Each Brainsucker Pod is taking 11 units of storage space, 11 * 16 = 176 units of storage space - a Alien Containment cell has 20 units of storage space.

**Comment by ayrtondenner** [comment]
> Although before anything we need to check the OG logic to save further increasing the workload with anything else missed regarding pods (they are fairly unique in being ammo, equipment and a live alien)


Just to confirm, I used the save file you provided and the Brainsucker life cycle is like you described: Brainsucker Pod -> Brainsucker (Alive) -> Brainsucker (Dead)

> Apologies again, it was my bad in testing https://github.com/OpenApoc/OpenApoc/pull/1372 - I assumed removing them from Alien Containment was needed, tested that it removed them, and failed to realise that they are mean to be in there just not consume all the capacity they do 😓

Checking in OG game and all Brainsucker stages take 1 slot of Alien Containment.

File: game/state/battle/battle.cpp [hunk 1]
```diff
@@ -3366,7 +3366,7 @@ void Battle::exitBattle(GameState &state)
 	}
 
 	// Give player vehicle a null cargo just so it comes back to base once
-	for (auto v : returningVehicles)
+	for (auto v : playerVehicles)
```
Comment (JonnyH) [inline game/state/battle/battle.cpp:3369]: If this is a different issue maybe a different PR is useful?

Keeping one-logical-chance-per-PR often helps later for reading logs or bisecting

File: game/ui/base/transactionscreen.cpp [hunk 2]
```diff
@@ -386,18 +386,27 @@ void TransactionScreen::populateControlsAlien()
...
+
 		if (!ae.second->bioStorage)
 		{
 			continue;
 		}
 		// Add alien
 		for (auto &b : state->player_bases)
 		{
-			// Removing brainsucker pod from alien containment list
+			auto alienTypeExistingControl = findControlById(type, alienTypeName);
```
Comment (JonnyH) [inline game/ui/base/transactionscreen.cpp:401]: Can be const?

File: game/ui/base/transactionscreen.cpp [hunk 3]
```diff
@@ -386,18 +386,27 @@ void TransactionScreen::populateControlsAlien()
 {
 	int leftIndex = getLeftIndex();
 	int rightIndex = getRightIndex();
+
 	for (auto &ae : state->agent_equipment)
 	{
+		auto &alienTypeName = ae.first;
```
Comment (JonnyH) [inline game/ui/base/transactionscreen.cpp:392]: Can be const?

File: game/ui/base/transactionscreen.cpp [hunk 4]
```diff
@@ -386,18 +386,27 @@ void TransactionScreen::populateControlsAlien()
...
 		// Add alien
 		for (auto &b : state->player_bases)
 		{
-			// Removing brainsucker pod from alien containment list
+			auto alienTypeExistingControl = findControlById(type, alienTypeName);
+
 			if (b.second->inventoryBioEquipment[ae.first] > 0 &&
-			    ae.first != "AEQUIPMENTTYPE_BRAINSUCKER_POD")
+
+			    // Removing brainsucker pod from alien containment list
```
Comment (JonnyH) [inline game/ui/base/transactionscreen.cpp:405]: I don't really like having a complex enough conditional so that comments are needed in the middle - can make a little hard to read.

Maybe this can be separated out so each is evaluated separately? Might need to reverse the comparisons?



e.g. something like:
```
if (b.second->inventoryBioEquipment[ae.first] == 0)
 continue;

//Skip brainsuckers
if (alienTypeName == "AEQUIPMENTYPE_BRAINSUCKER_POD")
  continue;

// Skip if it's already added
if (alienTypeExistingControl)
  continue;

// Create the control
auto control = ... etc etc etc
```

Does that make the logic clearer?

**Review by JonnyH — CHANGES_REQUESTED** [review]

File: game/ui/base/transactionscreen.cpp (hunk 4 above)
Comment (JonnyH) [reply game/ui/base/transactionscreen.cpp:405]: Though some things on this list may be removed by #1381 anyway :P

File: game/state/battle/battle.cpp (hunk 1 above)
Comment (ayrtondenner) [reply game/state/battle/battle.cpp:3369]: This was wrongly copied from https://github.com/OpenApoc/OpenApoc/pull/1379

File: game/ui/base/transactionscreen.cpp (hunk 2 above)
Comment (ayrtondenner) [reply game/ui/base/transactionscreen.cpp:401]: Even if the variable will have a new value for every loop run, is still advised to create it as const?

Comment (JonnyH) [reply game/ui/base/transactionscreen.cpp:401]: If it's not changed after declaration, I'd mark it "const".

I generally see that const *should* be the default, as it means you know at a glance it won't change value later in that block.

File: game/state/battle/battle.cpp (hunk 1 above)
Comment (ayrtondenner) [reply game/state/battle/battle.cpp]: Done, this now is reverted.

File: game/ui/base/transactionscreen.cpp (hunk 2 above)
Comment (ayrtondenner) [reply game/ui/base/transactionscreen.cpp]: Updated to const:

https://github.com/OpenApoc/OpenApoc/blob/12f960b12bf8b7d40fd104f027fedb298ccdcd30/game/ui/base/transactionscreen.cpp#L401

File: game/ui/base/transactionscreen.cpp (hunk 3 above)
Comment (ayrtondenner) [reply game/ui/base/transactionscreen.cpp]: Updated to const:

https://github.com/OpenApoc/OpenApoc/blob/12f960b12bf8b7d40fd104f027fedb298ccdcd30/game/ui/base/transactionscreen.cpp#L390-L392

File: game/ui/base/transactionscreen.cpp (hunk 4 above)
Comment (ayrtondenner) [reply game/ui/base/transactionscreen.cpp]: I reworked the condition to avoid having so many nested conditions. I also removed the outdated "Brainsucker Pod" reference:

https://github.com/OpenApoc/OpenApoc/blob/12f960b12bf8b7d40fd104f027fedb298ccdcd30/game/ui/base/transactionscreen.cpp#L399-L416
