### PR TITLE
fix hazard removal while iterating

### LINKED ISSUE #528: [Crash] on a alien spotted mission (Segmentation fault)
Crash during the mission in real time mode

gdb listing
`Thread 1 "main" received signal SIGSEGV, Segmentation fault.
OpenApoc::BattleHazard::update (this=0x60000000d, state=..., ticks=1)
    at /home/atrosha/OpenApoc/game/state/battle/battlehazard.cpp:490
490		if (ticksUntilVisible > 0)
(gdb) info stack
#0  OpenApoc::BattleHazard::update (this=0x60000000d, state=..., ticks=1)
    at /home/atrosha/OpenApoc/game/state/battle/battlehazard.cpp:490
#1  0x00000000007378f1 in OpenApoc::Battle::update (this=<optimized out>, 
    state=..., ticks=1)
    at /home/atrosha/OpenApoc/game/state/battle/battle.cpp:1675
#2  0x00000000008aa757 in OpenApoc::GameState::update (this=0x5989410, ticks=1)
    at /home/atrosha/OpenApoc/game/state/gamestate.cpp:959
#3  0x000000000052bf2d in OpenApoc::BattleView::update (this=<optimized out>)
    at /home/atrosha/OpenApoc/game/ui/tileview/battleview.cpp:1443
#4  0x00000000004569b8 in OpenApoc::Framework::run (this=0xfd14d0, 
    initialStage=...) at /home/atrosha/OpenApoc/framework/framework.cpp:584
#5  0x000000000043a1d4 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/atrosha/OpenApoc/game/main.cpp:26`

### PR DESCRIPTION
**Pull request by FranciscoDA**
Fixes #528

### CODE REVIEW

File: game/state/battle/battlehazard.h [hunk 1]
```diff
@@ -50,12 +50,13 @@ class BattleHazard : public std::enable_shared_from_this<BattleHazard>
 	            bool fireSmoke = false);
 	void grow(GameState &state);
 	void applyEffect(GameState &state);
-	void die(GameState &state, bool violently = true);
+	void die(GameState &state, bool violently, bool remove);
```
Comment (JonnyH) [inline game/state/battle/battlehazard.h]: I don't like unnamed flags changing function behaviour - it's very non-obvious when looking at the caller what "doThing(true)" and "doThing(false)" do, and easy to miss typos.

Maybe a "dieAndRemove()" call instead? Internally that can just call die() then remove?
